spring:
  cache:
    #设置缓存为 Redis
    type: redis
  redis:
    host: 192.168.0.224
    #指定缓存库
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 最大等待时间 -1ms表示没有限制阻塞等待时间
        max-wait: 10000
        #最大空闲数量
        max-idle: 4
        # 最小空闲数量
        min-idle: 0
    port: 6379
    password: root
    # redis超时时间
    timeout: 100000
mybatis-plus:
  mapper-locations: classpath:mapper