server:
  port: 8080
  servlet:
    context-path: /actuator
#访问端口，需要密码
spring:
  security:
    user:
      name: root
      password: root

#区分系统的端点信息接口的
management:
  server:
    port: 8090
    servlet:
      context-path: /sys
  #设置为"always"可以显示硬盘使用情况和线程情况
  endpoint:
    health:
      show-details: always
  # 设置端点暴露的哪些内容，默认["health","info"]，设置"*"代表暴露所有可访问的端点
  endpoints:
    web:
      exposure:
        include: '*'